# Generated by Django 3.2.6 on 2021-08-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
