# Generated by Django 3.2.6 on 2021-08-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_enquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enquete',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
