# Generated by Django 3.2.6 on 2021-09-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210927_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete',
            name='pageupdate',
            field=models.BooleanField(default=False),
        ),
    ]
