# Generated by Django 3.2.6 on 2022-01-18 19:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_dimaiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimaiz',
            name='slug',
        ),
        migrations.AlterField(
            model_name='dimaiz',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
