# Generated by Django 3.2.6 on 2022-02-08 17:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220208_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circular',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tabelaprecos',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
